### PR TITLE
Feature/content type settings

### PR DESCRIPTION
**Pull request by benschi11**
With this modifications you can now set tokenized default values on your contenttype.

Settings

### CODE REVIEW

**Comment by bhavinbdoshi** [comment]
I am working on integrating this for both Orchard 1.8.1/2 and 1.9

**Comment by Piedone** [comment]
Any update on this @bhavinbdoshi ?

**Comment by bhavinbdoshi** [comment]
Hi Zoltan, 
Working on it. Should have a release by November 6.

**Comment by Piedone** [comment]
Thank you @bhavinbdoshi . Looking forward to it.

**Comment by Piedone** [comment]
Any news on this @bhavinbdoshi ?

**Comment by bhavinbdoshi** [comment]
This has been merged to Module version 1.8 (For Orchard 1.8) and Module Version 1.9 (For Orchard 1.9).

**Comment by bhavinbdoshi** [comment]
Hi Zoltan,

This has been pushed to gallery.
Let me know if you have any questions.

Thanks,
Bhavin

**Comment by Piedone** [comment]
Thank you!

**Pull request closed without merging**
